version: '2'
services:
  db:
    image: mysql:5.6
    volumes:
      - "/my/custom:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Macnica123
 
  wordpress:
    depends_on:
      - db
    image: wordpress:php7.2
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: 172.30.1.2:3306
      WORDPRESS_DB_PASSWORD: Macnica123
